### Editar un evento (PUT)

# Simular PUT con nuevos datos del evento

PUT http://localhost:5000/eventos/4
Content-Type: application/json

{
  "nombre": "Evento actualizado",
  "ubicacion": "Nueva ubicación actualizada",
  "fecha_inicio": "2025-05-20T10:00:00",
  "fecha_fin": "2025-05-20T18:00:00",
  "descripcion": "Descripción actualizada del evento."
}
